openapi: 3.0.1
info:
  title: 'MAD API'
  description: |
    # Introduction

    This is meant to serve as developer documentation for the MAD Platform API - mad-api.
    Name – mad-api
    Github Repository - [equinor/mad-api](https://github.com/equinor/mad-api)
    Radix Console - [mad-api | Radix Web Console](https://console.radix.equinor.com/applications/mad-api)

    # API Overview

    ## Description

    Platform API having common functionalities used by multiple applications across the DSD and DFW ecosystem.