name: OpenAPI linting with spectral
# Triggered on push for yaml OpenAPI contracts for all branches or manually
# Spectral: https://github.com/stoplightio/spectral

on: 
  workflow_dispatch:
  push:
    paths:
    - 'openapi-contract/*.yaml'

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4
      # Run Spectral
      - uses: stoplightio/spectral-action@v0.8.8
        with:
          file_glob: 'openapi-contract/*.yaml'
          spectral_ruleset: 'openapi-linter/.spectral.yml'